spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/security}
    username: ${DB_URL:postgres}
    password: ${DB_PASSWORD:panama09}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ms-security

server:
  port: 8087

## Configuracion del cliente de Eureka
eureka:
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:ms-security}
    non-secure-port-enabled: false
    secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

saviasoft:
  app:
    frontend:
      url: ${FRONTEND_URL:http://localhost:3030}
  email:
    host: smtp.gmail.com
    port: 587
    username: seminario1fiec@gmail.com
    password: htgqxdxdfyreehxg